name: session_manager
description: "Session Manager"
homepage: https://wiki.gnome.org/Projects/SessionManagement
repository: https://github.com/canonical/session_manager.dart
issue_tracker: https://github.com/canonical/session_manager.dart/issues
version: 0.0.1

environment:
  sdk: ">=2.17.0 <3.0.0"

platforms:
  linux:

dependencies:
  dbus: ^0.7.3

dev_dependencies:
  build_runner: ^2.2.0
  lints: ^2.0.0
  mockito: ^5.3.2